defaults: &defaults
  adapter: mysql
  username: root
  password: 
  socket: /tmp/mysql.sock
  reconnect: true

development:
  database: c4c_pulse_dev
  <<: *defaults

test:
  database: mt_test
  <<: *defaults

production:
  database: c4c_pulse_dev
  <<: *defaults

ciministry_development:
  database: cim_prod
  <<: *defaults

ciministry_production:
  database: ciministry
  <<: *defaults

authservice_development:
  database: authservice
  <<: *defaults

authservice_production:
  database: authservice
  <<: *defaults

