defaults: &defaults
  adapter: mysql
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  database: pulse_stage_emu
  <<: *defaults

test:
  database: mt_test
  <<: *defaults

production:
  database: emu
  <<: *defaults

ciministry_development:
  database: ciministry
  <<: *defaults

ciministry_production:
  database: ciministry
  <<: *defaults

authservice_development:
  database: authservice
  <<: *defaults

authservice_production:
  database: authservice
  <<: *defaults

